title: CIT Minor Portfolio
description: A portfolio showcasing the labs and projects completed during my CIT Minor program.
theme: jekyll-theme-minimal


![Portfolio Image](images/Project7.jpg)

Welcome to my CIT Minor portfolio. Here, you'll find links to my labs and projects, each with a brief description of their purpose and content.
