title: CIT Minor Portfolio
description: A portfolio showcasing the labs and projects completed during my CIT Minor program.
theme: jekyll-theme-minimal


![Portfolio Image](downloads/Project7.png)

Welcome to my CIT Minor portfolio. Here, you'll find links to my labs and projects, each with a brief description of their purpose and content.

title: CIT 281 Lab 1
description: Details about CIT 281 Lab 1
theme: jekyll-theme-minimal

title: CIT 281 Lab 2
description: Details about CIT 281 Lab 2
theme: jekyll-theme-minimal

title: CIT 281 Project 1
description: Details about CIT 281 Project 1
theme: jekyll-theme-minimal

title: CIT 281 Lab 3
description: Details about CIT 281 Lab 3
theme: jekyll-theme-minimal

title: CIT 281 Project 2
description: Details about CIT 281 Project 2
theme: jekyll-theme-minimal

title: CIT 281 Lab 4
description: Details about CIT 281 Lab 4
theme: jekyll-theme-minimal

title: CIT 281 Lab 5
description: Details about CIT 281 Lab 5
theme: jekyll-theme-minimal

title: CIT 281 Project 3
description: Details about CIT 281 Project 3
theme: jekyll-theme-minimal

title: CIT 281 Lab 6
description: Details about CIT 281 Lab 6
theme: jekyll-theme-minimal

title: CIT 281 Project 4
description: Details about CIT 281 Project 4
theme: jekyll-theme-minimal

title: CIT 281 Lab 7
description: Details about CIT 281 Lab 7
theme: jekyll-theme-minimal

title: CIT 281 Project 5
description: Details about CIT 281 Project 5
theme: jekyll-theme-minimal

title: CIT 281 Lab 8
description: Details about CIT 281 Lab 8
theme: jekyll-theme-minimal

title: CIT 281 Project 6
description: Details about CIT 281 Project 6
theme: jekyll-theme-minimal

title: CIT 281 Lab 9
description: Details about CIT 281 Lab 9
theme: jekyll-theme-minimal












